"""
IEC61850 MMS(Manufacturing Message Specification)
"""

from __future__ import print_function
from scapy.packet import bind_layers, bind_bottom_up
from scapy.asn1packet import ASN1_Packet
from scapy.asn1fileds import ASN1F_INTEGER, ASN1F_IPADDRESS, ASN1F_OID, \
        ASN1F_SEQUENCE, ASN1F_SEQUENCE_OF, ASN1F_STRING, ASN1F_TIME_TICKS, \
        ASN1F_enum_INTEGER, ASN1F_filed, ASN1F_CHOICE
from scapy.asn1.asn1 import ASN1_Class_UNIVERSAL, ASN1_Codecs, ASN1_NULL, \
        ASN1_SEQUENCE
from scapy.asn1.ber import BERcodec_SEQUENCE
from scapy.sendrecv import sr1
from scapy.volatile import RandSHort, IntAutoTIme
from scapy.layers.inet import UDP, IP, ICMP

from scapy.asn1.mib impot conf

################
# IEC61850 MMS #
################

class ASN1_Class_MMS(ASN1_Class_UNIVERSAL):
    name = "MMS"

    #MmsPdu
    CONFIRMED_REQUEST_PDU = 0xa0
    CONFIRMED_RESPONSE_PDU = 0xa1
    UNCONFIRMED_PDU = 0xa3
    INITIATE_REQUEST_PDU = 0xa8
    INITIATE_RESPONSE_PDU = 0xa9
    INITIATE_ERROR_PDU = 0xaa

    #UnconfirmedService
    INFORMATION_REPORT = 0xa0

    #ConfirmedServiceRequest
    GET_NAME_LIST_REQUEST = 0xa1
    READ_REQUEST = 0xa4
    WRITE_REQUEST = 0xa5
    GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST = 0xa6
    DEFINE_NAMED_VARIABLE_LIST_REQUEST = 0xab
    GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST = 0xac
    DELETE_NAMED_VARIABLE_LIST_REQUEST = 0xad

    #ConfirmedServiceResponse
    GET_NAME_LIST_RESPONSE = 0xa1
    READ_RESPONSE = 0xa4
    WRITE_RESPONSE = 0xa5
    GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE = 0xa6
    DEFINE_NAMED_VARIABLE_LIST_RESPONSE = 0xab
    GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE = 0xac
    DELETE_NAMED_VARIABLE_LIST_RESPONSE = 0xad

    #ObjectName
    VMD_SPECIFIC = 0x80
    DOMAIN_SPECIFIC = 0xa1
    AA_SPECIFIC = 0x82

    #InitiateRequestPdu
    LOCAL_DETAIL_CALLING = 0x80
    PROPOSED_MAX_SERV_OUTSTANDING_CALLING = 0x81
    PROPOSED_MAX_SERV_OUTSTANDING_CALLED = 0x82
    PROPOSED_DATA_STRUCTURE_NESTING_LEVEL = 0x83
    MMS_INIT_REQUEST_DETAIL = 0xa4

    #InitRequestDetail
    PROPOSED_VERSION_NUMBER = 0x80
    PROPOSED_PARAMETER_CBB = 0x81
    SERVICES_SUPPORTED_CALLING = 0x82

    #InitiateResponsePdu
    LOCAL_DETAIL_CALLED = 0x80
    NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING = 0x81
    NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED = 0x82
    NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL = 0x83
    INIT_RESPONSE_DETAIL = 0xa4

    #InitResponseDetail
    NEGOTIATED_VERSION_NUMBER = 0x80
    NEGOTIATED_PARAMETER_CBB = 0x81
    SERVICES_SUPPORTED_CALLED = 0x82

    #ServiceError
    ERROR_CLASS = 0xa0
    ADDITIONAL_CODE = 0x81
    ADDITIONAL_DESCRIPTION = 0x82

    #errorClass
    VMD_STATE = 0x80
    APPLICATION_REFERENCE = 0x81
    DEFINITION = 0x82
    RESOURCE = 0x83
    SERVICE = 0x84
    SERVICE_PREEMPT = 0x85
    TIME_RESOLUTION = 0x86
    ACCESS = 0x87
    INITIATE = 0x88
    CONCLUDE = 0x89
    CANCEL = 0x8a
    FILE = 0x8b
    OTHERS = 0x8c

    #GetNameListRequest
    OBJECT_CLASS = 0xa0
    OBJECT_SCOPE = 0xa1
    CONTINUE_AFTER = 0x82

    #objectScope
    VMD_SPECIFIC = 0x80
    DOMAIN_SPECIFIC = 0x81
    AA_SPECIFIC = 0x82

    #ObjectClass
    BASIC_OBJECT_CLASS = 0x80

    #GetNameListResponse
    LIST_OF_IDENTIFIER = 0xa0
    MORE_FOLLOWS = 0x81

    ##TypeSpecification
    TYPE_SPECIFICATION_ARRAY = 0xa1
    TYPE_SPECIFICATION_STRUCTURE = 0xa2
    TYPE_SPECIFICATION_BOOLEAN_ = 0x83
    TYPE_SPECIFICATION_BIT_STRING = 0x84
    TYPE_SPECIFICATION_INTEGER = 0x85
    TYPE_SPECIFICATION_UNSIGNED = 0x86
    TYPE_SPECIFICATION_FLOATING_POINT = 0xa7
    TYPE_SPECIFICATION_OCTET_STRING = 0x89
    TYPE_SPECIFICATION_VISIBLE_STRING = 0x8a
    TYPE_SPECIFICATION_BINARY_TIME = 0x8c
    TYPE_SPECIFICATION_MMS_STRING = 0x90
    TYPE_SPECIFICATION_UTC_TIME = 0x91

    #array
    ARRAY_PACKED = 0x80
    ARRAY_NUMBER_OF_ELEMENTS = 0x81
    ARRAY_ELEMENT_TYPE = 0xa2

    #structure
    STRUCTURE_PACKED = 0x80
    STRUCTURE_COMPONENTS = 0xa1

    #StructComponent
    STRUCTURE_COMPONENT_COMPONENT_NAME = 0x80
    STRUCTURE_COMPONENT_COMPONENT_TYPE = 0xa1

    #AlternateAccess
    ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS = 0xa0
    ALTERNATE_ACCESS_COMPONENT = 0x81
    ALTERNATE_ACCESS_INDEX = 0x82
    ALTERNATE_ACCESS_INDEX_RANGE = 0xa3
    ALTERNATE_ACCESS_ALL_ELEMENTS = 0x84
    ALTERNATE_ACCESS_NAMED = 0xa5

    #accessSelection
    ACCESS_SELECTION_COMPONENT = 0x80
    ACCESS_SELECTION_INDEX = 0x81
    ACCESS_SELECTION_INDEX_RANGE = 0xa2
    ACCESS_SELECTION_ALL_ELEMENTS = 0x83

    #indexRange
    LOW_INDEX = 0x80
    NUMBER_OF_ELEMENTS = 0x81

    #named
    NAMED_COMPONENT_NAME = 0x80

    #AlternateAccessSelection
    ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS = 0xa0
    ALTERNATE_ACCESS_SELECTION_COMPONENT = 0x81
    ALTERNATE_ACCESS_SELECTION_INDEX = 0x82
    ALTERNATE_ACCESS_SELECTION_INDEX_RANGE = 0xa3
    ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS = 0x84

    #selectAlternateAccess
    SELECT_ALTERNATE_ACCESS_COMPONENT = 0x80
    SELECT_ALTERNATE_ACCESS_INDEX = 0x81
    SELECT_ALTERNATE_ACCESS_INDEX_RANGE = 0xa2
    SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS = 0x83

    #indexRnage
    LOW_INDEX = 0x80
    NUMBER_OF_ELEMENTS = 0x81

    #IndexRangeSeq
    LOW_INDEX = 0x80
    NUMBER_OF_ELEMENTS = 0x81

    #ReadRequest
    READ_REQUEST_SPECIFICATION_WITH_RESULT = 0x80
    READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION = 0xa1

    #ReadResponse
    READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION = 0xa0
    READ_RESPONSE_LIST_OF_ACCESS_RESULT = 0xa1

    #WriteRequest
    LIST_OF_DATA = 0xa0

    #WriteResponse
    FAILURE = 0x80
    SUCCESS = 0x81

    #GetVariableAccessAttributesRequest
    NAME = 0xa0

    #GetVariableAccessAttributesResponse
    MMS_DELETABLE = 0x80
    TYPE_SPECIFICATION = 0xa2

    #InformationReport
    INFORMATION_REPORT_LIST_OF_ACCESS_RESULT = 0xa0

    #DefineNamedVariableListRequest
    DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE = 0xa0

    #GetNamedVariableListAttributesResponse
    MMS_DELETABLE = 0x80
    GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE = 0xa1

    #DeleteNamedVariableListRequest
    SCOPE_OF_DELETE = 0x80
    LIST_OF_VARIABLE_LIST_NAME = 0xa1
    DOMAIN_NAME = 0x82

    #DeleteNamedVariableListResponse
    NUMBER_MATCHED = 0x80
    NUMBER_DELETED = 0x81

    #AccessResult
    FAILURE = 0x80

    #Data
    DATA_ARRAY = 0xa1
    DATA_STRUCTURE = 0xa2
    DATA_BOOLEAN_ = 0x83
    DATA_BIT_STRING = 0x84
    DATA_INTEGER = 0x85
    DATA_UNSIGNED = 0x86
    DATA_FLOATING_POINT = 0x87
    DATA_OCTET_STRING = 0x89
    DATA_VISIBLE_STRING = 0x8a
    DATA_BINARY_TIME = 0x8c
    DATA_MMS_STRING = 0x90
    DATA_UTC_TIME = 0x91

    #VariableAccessSpecification
    VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE = 0xa0
    VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME = 0xa1

    #VariableDef
    VARIABLE_DEF_ALTERNATE_ACCESS = 0xa5

    #VariableSpecification
    NAME = 0xa0

    #ScatteredAccessDescription
    SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME = 0x80
    SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION = 0xa1
    SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS = 0xa2


#MmsPdu
class ASN1_CONFIRMED_REQUEST_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.CONFIRMED_REQUEST_PDU

class ASN1_CONFIRMED_RESPONSE_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.CONFIRMED_RESPONSE_PDU

class ASN1_UNCONFIRMED_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.UNCONFIRMED_PDU

class ASN1_INITIATE_REQUEST_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_REQUEST_PDU

class ASN1_INITIATE_RESPONSE_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_RESPONSE_PDU

class ASN1_INITIATE_ERROR_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_ERROR_PDU

#UnconfirmedService
class ASN1_INFORMATION_REPORT(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INFORMATION_REPORT

#ConfirmedServiceRequest
class ASN1_GET_NAME_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_REQUEST

class ASN1_READ_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.READ_REQUEST

class ASN1_WRITE_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_REQUEST

class ASN1_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST(ASN1_CHOICE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST

class ASN1_DEFINE_NAMED_VARIABLE_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_REQUEST

class ASN1_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST(ASN1_CHOICE):
    tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST

class ASN1_DELETE_NAMED_VARIABLE_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_REQUEST

#ConfirmedServiceResponse
class ASN1_GET_NAMED_LIST_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAMED_LIST_RESPONSE

class ASN1_READ_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.READ_RESPONSE

class ASN1_WRITE_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_RESPONSE

class ASN1_GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE

class ASN1_DEFINE_NAMED_VARIABLE_LIST_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_RESPONSE


# [ASN1 fileds] #

class ASN1F_MMS_PDU_CONFIRMED_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.PDU_CONFIRMED_REQUEST

class ASN1F_MMS_PDU_CONFIRMED_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.PDU_CONFIRMED_RESPONSE

class ASN1F_MMS_PDU_UNCONFIRMED(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.PDU_UNCONFIRMED

class ASN1F_MMS_PDU_INITIATE_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.PDU_INITIATE_REQUEST

class ASN1F_MMS_PDU_INITIATE_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.PDU_INITIATE_RESPONSE

class ASN1F_MMS_PDU_INITIATE_ERROR(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.PDU_INITIATE_ERROR


#ConfirmedSerivceRequest
class ASN1F_MMS_GET_NAME_LIST_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_REQUEST
    tag = 0xa1

class ASN1F_MMS_READ_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.READ_QUEST
    tag = 0xa4

class ASN1F_MMS_WRITE_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_REQUEST
    tag = 0xa5

class ASN1F_MMS_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST
    tag = 0xa6

class ASN1F_MMS_DEFINE_NAME_VARIABLE_LIST_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_REQUEST
    tag = 0xab

class ASN1F_MMS_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST
    tag = 0xac

class ASN1F_MMS_DELETE_NAMED_VARIABLE_LIST_REQUEST(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST
    tag = 0xad

#ConfirmedSerivceResponse
class ASN1F_MMS_GET_NAME_LIST_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_RESPONSE
    tag = 0xa1

class ASN1F_MMS_READ_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.READ_RESPONSE
    tag = 0xa4

class ASN1F_MMS_WRITE_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_RESPONSE
    tag = 0xa5

class ASN1F_MMS_GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE
    tag = 0xa6

class ASN1F_MMS_DEFINE_NAME_VARIABLE_LIST_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_RESPONSE
    tag = 0xab

class ASN1F_MMS_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE
    tag = 0xac

class ASN1F_MMS_DELETE_NAMED_VARIABLE_LIST_RESPONSE(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE
    tag = 0xad

#ObjectClass
class ASN1F_MMS_OBJECT_CLASS(ASN1F_SEQUENCE):
    tag = ASN1_Class_MMS.OBJECT_CLASS
    tag = 0xa0

#basicObjectClass
class ASN1F_MMS_BASIC_OBJECT_CLASS(ASN1F_)

# [MMS Packet] #

class MMSobject_class(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_MMS_OBJECT_CLASS(ASN1F_BASIC_OBJECT_CLASS)

class MMSget_name_list_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_GET_NAME_LIST_SEQUENCE(ASN1F_OBJECT_CLASS,
                                            ASN1F_OBJECT_SCOPE)

class MMSconfirmed_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_MMS_PDU_CONFIRMED_REQUEST(ASN1F_INTEGER("invokeID"),
                                                ASN1F_CHOICE("ConfirmedSerivceRequest", ASN1F_GET_NAME_LSIT_REQUEST(),
                                                    ASN1F_GET_NAME_LIST_REQUEST, ASN1F_READ_REQUEST, ASN1F_WRITE_REQUEST, 
                                                    ASN1F_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST, ASN1F_DEFINE_NAMED_VARIABLE_LIST_REQUEST, 
                                                    ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST, ASN1F_DELETE_NAMED_VARIABLE_LIST_REQUEST))

class MMSconfirmed_response(ASN1_Packet):
    pass

class MMSunconfirmed(ASN1_Packet):
    pass

class MMSinitiate_request(ASN1_Packet):
    pass

class MMSinitiate_response(ASN1_Packet):
    pass

class MMSinitiate_error(ASN1_Packet):
    pass

class MMS(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_CHOICE("PDU", MMSconfirmed_request(),
            MMSconfirmed_request, MMSconfirmed_response, MMSunconfirmed,
            MMSinitiate_request, MMSinitiate_response, MMSinitiate_error)

