"""
IEC61850 MMS(Manufacturing Message Specification)
"""

from __future__ import print_function
from scapy.all import *

################
# IEC61850 MMS #
################

class ASN1_Class_MMS(ASN1_Class_UNIVERSAL):
    name = "MMS"

    #MmsPdu
    CONFIRMED_REQUEST_PDU = 0xa0
    CONFIRMED_RESPONSE_PDU = 0xa1
    UNCONFIRMED_PDU = 0xa3
    INITIATE_REQUEST_PDU = 0xa8
    INITIATE_RESPONSE_PDU = 0xa9
    INITIATE_ERROR_PDU = 0xaa

    #UnconfirmedService
    INFORMATION_REPORT = 0xa0

    #ConfirmedServiceRequest
    GET_NAME_LIST_REQUEST = 0xa1
    READ_REQUEST = 0xa4
    WRITE_REQUEST = 0xa5
    GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST = 0xa6
    DEFINE_NAMED_VARIABLE_LIST_REQUEST = 0xab
    GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST = 0xac
    DELETE_NAMED_VARIABLE_LIST_REQUEST = 0xad

    #ConfirmedServiceResponse
    GET_NAME_LIST_RESPONSE = 0xa1
    READ_RESPONSE = 0xa4
    WRITE_RESPONSE = 0xa5
    GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE = 0xa6
    DEFINE_NAMED_VARIABLE_LIST_RESPONSE = 0xab
    GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE = 0xac
    DELETE_NAMED_VARIABLE_LIST_RESPONSE = 0xad

    #ObjectName
    VMD_SPECIFIC = 0x80
    DOMAIN_SPECIFIC = 0xa1
    AA_SPECIFIC = 0x82

    #InitiateRequestPdu
    LOCAL_DETAIL_CALLING = 0x80
    PROPOSED_MAX_SERV_OUTSTANDING_CALLING = 0x81
    PROPOSED_MAX_SERV_OUTSTANDING_CALLED = 0x82
    PROPOSED_DATA_STRUCTURE_NESTING_LEVEL = 0x83
    MMS_INIT_REQUEST_DETAIL = 0xa4

    #InitRequestDetail
    PROPOSED_VERSION_NUMBER = 0x80
    PROPOSED_PARAMETER_CBB = 0x81
    SERVICES_SUPPORTED_CALLING = 0x82

    #InitiateResponsePdu
    LOCAL_DETAIL_CALLED = 0x80
    NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING = 0x81
    NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED = 0x82
    NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL = 0x83
    MMS_INIT_RESPONSE_DETAIL = 0xa4

    #InitResponseDetail
    NEGOTIATED_VERSION_NUMBER = 0x80
    NEGOTIATED_PARAMETER_CBB = 0x81
    SERVICES_SUPPORTED_CALLED = 0x82

    #ServiceError
    ERROR_CLASS = 0xa0
    ADDITIONAL_CODE = 0x81
    ADDITIONAL_DESCRIPTION = 0x82

    #errorClass
    VMD_STATE = 0x80
    APPLICATION_REFERENCE = 0x81
    DEFINITION = 0x82
    RESOURCE = 0x83
    SERVICE = 0x84
    SERVICE_PREEMPT = 0x85
    TIME_RESOLUTION = 0x86
    ACCESS = 0x87
    INITIATE = 0x88
    CONCLUDE = 0x89
    CANCEL = 0x8a
    FILE = 0x8b
    OTHERS = 0x8c

    #GetNameListRequest
    OBJECT_CLASS = 0xa0
    OBJECT_SCOPE = 0xa1
    CONTINUE_AFTER = 0x82

    #objectScope
    OBJECT_SCOPE_VMD_SPECIFIC = 0x80
    OBJECT_SCOPE_DOMAIN_SPECIFIC = 0x81
    OBJECT_SCOPE_AA_SPECIFIC = 0x82

    #ObjectClass
    BASIC_OBJECT_CLASS = 0x80

    #GetNameListResponse
    LIST_OF_IDENTIFIER = 0xa0
    MORE_FOLLOWS = 0x81

    ##TypeSpecification
    TYPE_SPECIFICATION_ARRAY = 0xa1
    TYPE_SPECIFICATION_STRUCTURE = 0xa2
    TYPE_SPECIFICATION_BOOLEAN_ = 0x83
    TYPE_SPECIFICATION_BIT_STRING = 0x84
    TYPE_SPECIFICATION_INTEGER = 0x85
    TYPE_SPECIFICATION_UNSIGNED = 0x86
    TYPE_SPECIFICATION_FLOATING_POINT = 0xa7
    TYPE_SPECIFICATION_OCTET_STRING = 0x89
    TYPE_SPECIFICATION_VISIBLE_STRING = 0x8a
    TYPE_SPECIFICATION_BINARY_TIME = 0x8c
    TYPE_SPECIFICATION_MMS_STRING = 0x90
    TYPE_SPECIFICATION_UTC_TIME = 0x91

    #array
    ARRAY_PACKED = 0x80
    ARRAY_NUMBER_OF_ELEMENTS = 0x81
    ARRAY_ELEMENT_TYPE = 0xa2

    #structure
    STRUCTURE_PACKED = 0x80
    STRUCTURE_COMPONENTS = 0xa1

    #StructComponent
    STRUCTURE_COMPONENT_COMPONENT_NAME = 0x80
    STRUCTURE_COMPONENT_COMPONENT_TYPE = 0xa1

    #AlternateAccess
    ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS = 0xa0
    ALTERNATE_ACCESS_COMPONENT = 0x81
    ALTERNATE_ACCESS_INDEX = 0x82
    ALTERNATE_ACCESS_INDEX_RANGE = 0xa3
    ALTERNATE_ACCESS_ALL_ELEMENTS = 0x84
    ALTERNATE_ACCESS_NAMED = 0xa5

    #accessSelection
    ACCESS_SELECTION_COMPONENT = 0x80
    ACCESS_SELECTION_INDEX = 0x81
    ACCESS_SELECTION_INDEX_RANGE = 0xa2
    ACCESS_SELECTION_ALL_ELEMENTS = 0x83

    #indexRange
    LOW_INDEX = 0x80
    NUMBER_OF_ELEMENTS = 0x81

    #named
    NAMED_COMPONENT_NAME = 0x80

    #AlternateAccessSelection
    ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS = 0xa0
    ALTERNATE_ACCESS_SELECTION_COMPONENT = 0x81
    ALTERNATE_ACCESS_SELECTION_INDEX = 0x82
    ALTERNATE_ACCESS_SELECTION_INDEX_RANGE = 0xa3
    ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS = 0x84

    #selectAlternateAccess
    SELECT_ALTERNATE_ACCESS_COMPONENT = 0x80
    SELECT_ALTERNATE_ACCESS_INDEX = 0x81
    SELECT_ALTERNATE_ACCESS_INDEX_RANGE = 0xa2
    SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS = 0x83

    #indexRnage
    LOW_INDEX = 0x80
    NUMBER_OF_ELEMENTS = 0x81

    #IndexRangeSeq
    LOW_INDEX = 0x80
    NUMBER_OF_ELEMENTS = 0x81

    #ReadRequest
    READ_REQUEST_SPECIFICATION_WITH_RESULT = 0x80
    READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION = 0xa1

    #ReadResponse
    READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION = 0xa0
    READ_RESPONSE_LIST_OF_ACCESS_RESULT = 0xa1

    #WriteRequest
    LIST_OF_DATA = 0xa0

    #WriteResponse
    FAILURE = 0x80
    SUCCESS = 0x81

    #GetVariableAccessAttributesRequest
    NAME = 0xa0

    #GetVariableAccessAttributesResponse
    MMS_DELETABLE = 0x80
    TYPE_SPECIFICATION = 0xa2

    #InformationReport
    INFORMATION_REPORT_LIST_OF_ACCESS_RESULT = 0xa0

    #DefineNamedVariableListRequest
    DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE = 0xa0

    #GetNamedVariableListAttributesResponse
    MMS_DELETABLE = 0x80
    GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE = 0xa1

    #DeleteNamedVariableListRequest
    SCOPE_OF_DELETE = 0x80
    LIST_OF_VARIABLE_LIST_NAME = 0xa1
    DOMAIN_NAME = 0x82

    #DeleteNamedVariableListResponse
    NUMBER_MATCHED = 0x80
    NUMBER_DELETED = 0x81

    #AccessResult
    FAILURE = 0x80

    #Data
    DATA_ARRAY = 0xa1
    DATA_STRUCTURE = 0xa2
    DATA_BOOLEAN_ = 0x83
    DATA_BIT_STRING = 0x84
    DATA_INTEGER = 0x85
    DATA_UNSIGNED = 0x86
    DATA_FLOATING_POINT = 0x87
    DATA_OCTET_STRING = 0x89
    DATA_VISIBLE_STRING = 0x8a
    DATA_BINARY_TIME = 0x8c
    DATA_MMS_STRING = 0x90
    DATA_UTC_TIME = 0x91

    #VariableAccessSpecification
    VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE = 0xa0
    VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME = 0xa1

    #VariableDef
    VARIABLE_DEF_ALTERNATE_ACCESS = 0xa5

    #VariableSpecification
    NAME = 0xa0

    #ScatteredAccessDescription
    SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME = 0x80
    SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION = 0xa1
    SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS = 0xa2



#MmsPdu
class ASN1_CONFIRMED_REQUEST_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.CONFIRMED_REQUEST_PDU

class ASN1_CONFIRMED_RESPONSE_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.CONFIRMED_RESPONSE_PDU

class ASN1_UNCONFIRMED_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.UNCONFIRMED_PDU

class ASN1_INITIATE_REQUEST_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_REQUEST_PDU

class ASN1_INITIATE_RESPONSE_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_RESPONSE_PDU

class ASN1_INITIATE_ERROR_PDU(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_ERROR_PDU


#UnconfirmedService
class ASN1_INFORMATION_REPORT(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.INFORMATION_REPORT

#ConfirmedServiceRequest

class ASN1_GET_NAME_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_REQUEST

class ASN1_READ_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.READ_REQUEST

class ASN1_WRITE_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_REQUEST

class ASN1_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST

class ASN1_DEFINE_NAMED_VARIABLE_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_REQUEST

class ASN1_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST

class ASN1_DELETE_NAMED_VARIABLE_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_REQUEST

#ConfirmedServiceResponse
class ASN1_GET_NAME_LIST_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_RESPONSE

class ASN1_READ_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.READ_RESPONSE

class ASN1_WRITE_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_RESPONSE

class ASN1_GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE

class ASN1_DEFINE_NAMED_VARIABLE_LIST_RESPONSE(ASN1_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_RESPONSE
	
class ASN1_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE
	
class ASN1_DELETE_NAMED_VARIABLE_LIST_RESPONSE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_RESPONSE

#ObjectName	
class ASN1_VMD_SPECIFIC(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.VMD_SPECIFIC

class ASN1_DOMAIN_SPECIFIC(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.DOMAIN_SPECIFIC
	
class ASN1_AA_SPECIFIC(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.AA_SPECIFIC

#InitiateRequestPdu
class ASN1_LOCAL_DETAIL_CALLING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.LOCAL_DETAIL_CALLING

class ASN1_PROPOSED_MAX_SERV_OUTSTANDING_CALLING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLING

class ASN1_PROPOSED_MAX_SERV_OUTSTANDING_CALLED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLED

class ASN1_PROPOSED_DATA_STRUCTURE_NESTING_LEVEL(ASN1_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_DATA_STRUCTURE_NESTING_LEVEL

class ASN1_MMS_INIT_REQUEST_DETAIL(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.MMS_INIT_REQUEST_DETAIL

#InitRequestDetail
class ASN1_PROPOSED_VERSION_NUMBER(ASN1_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_VERSION_NUMBER

class ASN1_PROPOSED_PARAMETER_CBB(ASN1_BIT_STRING):
	tag = ASN1_Class_MMS.PROPOSED_PARAMETER_CBB

class ASN1_SERVICES_SUPPORTED_CALLING(ASN1_BIT_STRING):
	tag = ASN1_Class_MMS.SERVICES_SUPPORTED_CALLING
	
#InitiateResponsePdu
class ASN1_LOCAL_DETAIL_CALLED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.LOCAL_DETAIL_CALLED

class ASN1_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING

class ASN1_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED

class ASN1_NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL

class ASN1_MMS_INIT_RESPONSE_DETAIL(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.MMS_INIT_RESPONSE_DETAIL

#InitResponseDetail
class ASN1_NEGOTIATED_VERSION_NUMBER(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_VERSION_NUMBER

class ASN1_NEGOTIATED_PARAMETER_CBB(ASN1_BIT_STRING):
	tag = ASN1_Class_MMS.NEGOTIATED_PARAMETER_CBB

class ASN1_SERVICES_SUPPORTED_CALLED(ASN1_BIT_STRING):
	tag = ASN1_Class_MMS.SERVICES_SUPPORTED_CALLED


#ServiceError
class ASN1_ERROR_CLASS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ERROR_CLASS
	
class ASN1_ADDITIONAL_CODE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.ADDITIONAL_CODE
	
class ASN1_ADDITIONAL_DESCRIPTION(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.ADDITIONAL_DESCRIPTION
	
#errorClass
class ASN1_VMD_STATE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.VMD_STATE

class ASN1_APPLICATION_REFERENCE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.APPLICATION_REFERENCE
	
class ASN1_DEFINITION(ASN1_INTEGER):
	tag = ASN1_Class_MMS.DEFINITION
	
class ASN1_RESOURCE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.RESOURCE
	
class ASN1_SERVICE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.SERVICE
	
class ASN1_SERVICE_PREEMPT(ASN1_INTEGER):
	tag = ASN1_Class_MMS.SERVICE_PREEMPT
	
class ASN1_TIME_RESOLUTION(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TIME_RESOLUTION
	
class ASN1_ACCESS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.ACCESS
	
class ASN1_INITIATE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.INITIATE
	
class ASN1_CONCLUDE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.CONCLUDE
	
class ASN1_CANCEL(ASN1_INTEGER):
	tag = ASN1_Class_MMS.CANCEL
	
class ASN1_FILE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.FILE
	
class ASN1_OTHERS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.OTHERS
	
#GetNameListRequest
class ASN1_OBJECT_CLASS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.OBJECT_CLASS
	
class ASN1_OBJECT_SCOPE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.OBJECT_SCOPE

class ASN1_CONTINUE_AFTER(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.CONTINUE_AFTER
	
#objectScope
class ASN1_OBJECT_SCOPE_VMD_SPECIFIC(ASN1_NULL):
	tag = ASN1_Class_MMS.OBJECT_SCOPE_VMD_SPECIFIC
	
class ASN1_OBJECT_SCOPE_DOMAIN_SPECIFIC(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.OBJECT_SCOPE_DOMAIN_SPECIFIC

class ASN1_OBJECT_SCOPE_AA_SPECIFIC(ASN1_NULL):
	tag = ASN1_Class_MMS.OBJECT_SCOPE_AA_SPECIFIC
	
#ObjectClass
class ASN1_BASIC_OBJECT_CLASS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.BASIC_OBJECT_CLASS

#GetNameListResponse
class ASN1_LIST_OF_IDENTIFIER(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.LIST_OF_IDENTIFIER

class ASN1_MORE_FOLLOWS(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.MORE_FOLLOWS

#TypeSpecification
class ASN1_TYPE_SPECIFICATION_ARRAY(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_ARRAY
	
class ASN1_TYPE_SPECIFICATION_STRUCTURE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_STRUCTURE
	
class ASN1_TYPE_SPECIFICATION_BOOLEAN_(ASN1_NULL):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BOOLEAN_
	
class ASN1_TYPE_SPECIFICATION_BIT_STRING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BIT_STRING
	
class ASN1_TYPE_SPECIFICATION_INTEGER(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_INTEGER
	
class ASN1_TYPE_SPECIFICATION_UNSIGNED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_UNSIGNED
	
class ASN1_TYPE_SPECIFICATION_FLOATING_POINT(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_FLOATING_POINT
	
class ASN1_TYPE_SPECIFICATION_OCTET_STRING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_OCTET_STRING
	
class ASN1_TYPE_SPECIFICATION_VISIBLE_STRING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_VISIBLE_STRING

class ASN1_TYPE_SPECIFICATION_BINARY_TIME(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BINARY_TIME
	
class ASN1_TYPE_SPECIFICATION_MMS_STRING(ASN1_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_MMS_STRING
	
class ASN1_TYPE_SPECIFICATION_UTC_TIME(ASN1_NULL):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_UTC_TIME

#array
class ASN1_ARRAY_PACKED(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.ARRAY_PACKED
	
class ASN1_ARRAY_NUMBER_OF_ELEMENTS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.ARRAY_NUMBER_OF_ELEMENTS
	
class ASN1_ARRAY_ELEMENT_TYPE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ARRAY_ELEMENT_TYPE
	
#structure
class ASN1_STRUCTURE_PACKED(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.STRUCTURE_PACKED
	
class ASN1_STRUCTURE_COMPONENTS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENTS


#StructComponent
class ASN1_STRUCTURE_COMPONENT_COMPONENT_NAME(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_NAME
	
class ASN1_STRUCTURE_COMPONENT_COMPONENT_TYPE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_TYPE


#AlternateAccess
class ASN1_ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS

class ASN1_ALTERNATE_ACCESS_COMPONENT(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_COMPONENT

class ASN1_ALTERNATE_ACCESS_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_INDEX

class ASN1_ALTERNATE_ACCESS_INDEX_RANGE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_TYPE

class ASN1_ALTERNATE_ACCESS_ALL_ELEMENTS(ASN1_NULL):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_ALL_ELEMENTS

class ASN1_ALTERNATE_ACCESS_NAMED(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_NAMED

#accessSelection
class ASN1_ACCESS_SELECTION_COMPONENT(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_COMPONENT

class ASN1_ACCESS_SELECTION_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_INDEX

class ASN1_ACCESS_SELECTION_INDEX_RANGE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_INDEX_RANGE

class ASN1_ACCESS_SELECTION_ALL_ELEMENTS(ASN1_NULL):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_ALL_ELEMENTS


#indexRange
class ASN1_LOW_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.LOW_INDEX

class ASN1_NUMBER_OF_ELEMENTS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS

	
#named
class ASN1_NAMED_COMPONENT_NAME(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.NAMED_COMPONENT_NAME

	
#AlternateAccessSelection
class ASN1_ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS
	
class ASN1_ALTERNATE_ACCESS_SELECTION_COMPONENT(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_COMPONENT
	
class ASN1_ALTERNATE_ACCESS_SELECTION_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_INDEX
	
class ASN1_ALTERNATE_ACCESS_SELECTION_INDEX_RANGE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_INDEX_RANGE
	
class ASN1_ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS(ASN1_NULL):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS


#selectAlternateAccess
class ASN1_SELECT_ALTERNATE_ACCESS_COMPONENT(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_COMPONENT
	
class ASN1_SELECT_ALTERNATE_ACCESS_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_INDEX
	
class ASN1_SELECT_ALTERNATE_ACCESS_INDEX_RANGE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_INDEX_RANGE
	
class ASN1_SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS(ASN1_NULL):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS


#indexRnage
class ASN1_LOW_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.LOW_INDEX
	
class ASN1_NUMBER_OF_ELEMENTS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS


#IndexRangeSeq
class ASN1_LOW_INDEX(ASN1_INTEGER):
	tag = ASN1_Class_MMS.LOW_INDEX
	
class ASN1_NUMBER_OF_ELEMENTS(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS

#ReadRequest
class ASN1_READ_REQUEST_SPECIFICATION_WITH_RESULT(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.READ_REQUEST_SPECIFICATION_WITH_RESULT
	
class ASN1_READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION


#ReadResponse
class ASN1_READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION
	
class ASN1_READ_RESPONSE_LIST_OF_ACCESS_RESULT(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.READ_RESPONSE_LIST_OF_ACCESS_RESULT
	

#WriteRequest
class ASN1_LIST_OF_DATA(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.LIST_OF_DATA	


#WriteResponse
class ASN1_FAILURE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.FAILURE

class ASN1_SUCCESS(ASN1_NULL):
	tag = ASN1_Class_MMS.SUCCESS

#GetVariableAccessAttributesRequest
class ASN1_NAME(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.NAME


#GetVariableAccessAttributesResponse
class ASN1_MMS_DELETABLE(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.MMS_DELETABLE

class ASN1_TYPE_SPECIFICATION(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION


#InformationReport
class ASN1_INFORMATION_REPORT_LIST_OF_ACCESS_RESULT(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.INFORMATION_REPORT_LIST_OF_ACCESS_RESULT


#DefineNamedVariableListRequest
class ASN1_DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE
	

#GetNamedVariableListAttributesResponse
class ASN1_MMS_DELETABLE(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.MMS_DELETABLE
	
class ASN1_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE
	

#DeleteNamedVariableListRequest
class ASN1_SCOPE_OF_DELETE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.SCOPE_OF_DELETE
	
class ASN1_LIST_OF_VARIABLE_LIST_NAME(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.LIST_OF_VARIABLE_LIST_NAME
	
class ASN1_DOMAIN_NAME(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.DOMAIN_NAME
	

#DeleteNamedVariableListResponse
class ASN1_NUMBER_MATCHED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_MATCHED
	
class ASN1_NUMBER_DELETED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_DELETED
	

#AccessResult
class ASN1_FAILURE(ASN1_INTEGER):
	tag = ASN1_Class_MMS.FAILURE


#Data
class ASN1_DATA_ARRAY(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.DATA_ARRAY
	
class ASN1_DATA_STRUCTURE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.DATA_STRUCTURE
	
class ASN1_DATA_BOOLEAN_(ASN1_BOOLEAN):
	tag = ASN1_Class_MMS.DATA_BOOLEAN_
	
class ASN1_DATA_BIT_STRING(ASN1_BIT_STRING):
	tag = ASN1_Class_MMS.DATA_BIT_STRING
	
class ASN1_DATA_INTEGER(ASN1_INTEGER):
	tag = ASN1_Class_MMS.DATA_INTEGER
	
class ASN1_DATA_UNSIGNED(ASN1_INTEGER):
	tag = ASN1_Class_MMS.DATA_UNSIGNED
	
class ASN1_DATA_FLOATING_POINT(ASN1_STRING):
	tag = ASN1_Class_MMS.DATA_FLOATING_POINT
	
class ASN1_DATA_OCTET_STRING(ASN1_STRING):
	tag = ASN1_Class_MMS.DATA_OCTET_STRING
	
class ASN1_DATA_VISIBLE_STRING(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.DATA_VISIBLE_STRING
	
class ASN1_DATA_BINARY_TIME(ASN1_STRING):
	tag = ASN1_Class_MMS.DATA_BINARY_TIME

class ASN1_DATA_MMS_STRING(ASN1_UTF8_STRING):
	tag = ASN1_Class_MMS.DATA_MMS_STRING
	
class ASN1_DATA_UTC_TIME(ASN1_STRING):
	tag = ASN1_Class_MMS.DATA_UTC_TIME
	
#VariableAccessSpecification
class ASN1_VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE
	
class ASN1_VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME
	

#VariableDef
class ASN1_VARIABLE_DEF_ALTERNATE_ACCESS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.VARIABLE_DEF_ALTERNATE_ACCESS
	

#VariableSpecification
class ASN1_NAME(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.NAME

#ScatteredAccessDescription
class ASN1_SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME(ASN1_ISO646_STRING):
	tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME
	
class ASN1_SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION
	
class ASN1_SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS(ASN1_SEQUENCE):
	tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS
	
	
	

# [BER codecs] #

#MmsPdu
class BERcodec_CONFIRMED_REQUEST_PDU(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.CONFIRMED_REQUEST_PDU

class BERcodec_CONFIRMED_RESPONSE_PDU(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.CONFIRMED_RESPONSE_PDU

class BERcodec_UNCONFIRMED_PDU(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.UNCONFIRMED_PDU

class BERcodec_INITIATE_REQUEST_PDU(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_REQUEST_PDU

class BERcodec_INITIATE_RESPONSE_PDU(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_RESPONSE_PDU

class BERcodec_INITIATE_ERROR_PDU(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.INITIATE_ERROR_PDU

#UnconfirmedService
class BERcodec_INFORMATION_REPORT(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.INFORMATION_REPORT

#ConfirmedServiceRequest
class BERcodec_GET_NAME_LIST_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_REQUEST

class BERcodec_READ_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.READ_REQUEST

class BERcodec_WRITE_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_REQUEST

class BERcodec_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST

class BERcodec_DEFINE_NAMED_VARIABLE_LIST_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_REQUEST

class BERcodec_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST

class BERcodec_DELETE_NAMED_VARIABLE_LIST_REQUEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_REQUEST

#ConfirmedServiceResponse
class BERcodec_GET_NAME_LIST_RESPONSE(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.GET_NAME_LIST_RESPONSE

class BERcodec_READ_RESPONSE(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.READ_RESPONSE

class BERcodec_WRITE_RESPONSE(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.WRITE_RESPONSE

class BERcodec_GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE

class BERcodec_DEFINE_NAMED_VARIABLE_LIST_RESPONSE(BERcodec_SEQUENCE):
    tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_RESPONSE
	
class BERcodec_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE
	
class BERcodec_DELETE_NAMED_VARIABLE_LIST_RESPONSE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_RESPONSE
	
class BERcodec_VMD_SPECIFIC(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.VMD_SPECIFIC

class BERcodec_DOMAIN_SPECIFIC(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.DOMAIN_SPECIFIC
	
class BERcodec_AA_SPECIFIC(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.AA_SPECIFIC

#InitiateRequestPdu
class BERcodec_LOCAL_DETAIL_CALLING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.LOCAL_DETAIL_CALLING

class BERcodec_PROPOSED_MAX_SERV_OUTSTANDING_CALLING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLING

class BERcodec_PROPOSED_MAX_SERV_OUTSTANDING_CALLED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLED

class BERcodec_PROPOSED_DATA_STRUCTURE_NESTING_LEVEL(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_DATA_STRUCTURE_NESTING_LEVEL

class BERcodec_MMS_INIT_REQUEST_DETAIL(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.MMS_INIT_REQUEST_DETAIL

#InitRequestDetail
class BERcodec_PROPOSED_VERSION_NUMBER(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.PROPOSED_VERSION_NUMBER

class BERcodec_PROPOSED_PARAMETER_CBB(BERcodec_BIT_STRING):
	tag = ASN1_Class_MMS.PROPOSED_PARAMETER_CBB

class BERcodec_SERVICES_SUPPORTED_CALLING(BERcodec_BIT_STRING):
	tag = ASN1_Class_MMS.SERVICES_SUPPORTED_CALLING
	
#InitiateResponsePdu
class BERcodec_LOCAL_DETAIL_CALLED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.LOCAL_DETAIL_CALLED

class BERcodec_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING

class BERcodec_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED

class BERcodec_NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL

class BERcodec_MMS_INIT_RESPONSE_DETAIL(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.MMS_INIT_RESPONSE_DETAIL

#InitResponseDetail
class BERcodec_NEGOTIATED_VERSION_NUMBER(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NEGOTIATED_VERSION_NUMBER

class BERcodec_NEGOTIATED_PARAMETER_CBB(BERcodec_BIT_STRING):
	tag = ASN1_Class_MMS.NEGOTIATED_PARAMETER_CBB

class BERcodec_SERVICES_SUPPORTED_CALLED(BERcodec_BIT_STRING):
	tag = ASN1_Class_MMS.SERVICES_SUPPORTED_CALLED
	
#ServiceError
class BERcodec_ERROR_CLASS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ERROR_CLASS
	
class BERcodec_ADDITIONAL_CODE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.ADDITIONAL_CODE
	
class BERcodec_ADDITIONAL_DESCRIPTION(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.ADDITIONAL_DESCRIPTION
	
#errorClass
class BERcodec_VMD_STATE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.VMD_STATE

class BERcodec_APPLICATION_REFERENCE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.APPLICATION_REFERENCE
	
class BERcodec_DEFINITION(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.DEFINITION
	
class BERcodec_RESOURCE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.RESOURCE
	
class BERcodec_SERVICE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.SERVICE
	
class BERcodec_SERVICE_PREEMPT(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.SERVICE_PREEMPT
	
class BERcodec_TIME_RESOLUTION(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TIME_RESOLUTION
	
class BERcodec_ACCESS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.ACCESS
	
class BERcodec_INITIATE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.INITIATE
	
class BERcodec_CONCLUDE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.CONCLUDE
	
class BERcodec_CANCEL(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.CANCEL
	
class BERcodec_FILE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.FILE
	
class BERcodec_OTHERS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.OTHERS

#GetNameListRequest
class BERcodec_OBJECT_CLASS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.OBJECT_CLASS
	
class BERcodec_OBJECT_SCOPE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.OBJECT_SCOPE

class BERcodec_CONTINUE_AFTER(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.CONTINUE_AFTER
	
#objectScope
class BERcodec_OBJECT_SCOPE_VMD_SPECIFIC(BERcodec_NULL):
	tag = ASN1_Class_MMS.OBJECT_SCOPE_VMD_SPECIFIC
	
class BERcodec_OBJECT_SCOPE_DOMAIN_SPECIFIC(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.OBJECT_SCOPE_DOMAIN_SPECIFIC

class BERcodec_OBJECT_SCOPE_AA_SPECIFIC(BERcodec_NULL):
	tag = ASN1_Class_MMS.OBJECT_SCOPE_AA_SPECIFIC
	
#ObjectClass
class BERcodec_BASIC_OBJECT_CLASS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.BASIC_OBJECT_CLASS
	
#GetNameListResponse
class BERcodec_LIST_OF_IDENTIFIER(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.LIST_OF_IDENTIFIER

class BERcodec_MORE_FOLLOWS(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.MORE_FOLLOWS

#TypeSpecification
class BERcodec_TYPE_SPECIFICATION_ARRAY(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_ARRAY
	
class BERcodec_TYPE_SPECIFICATION_STRUCTURE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_STRUCTURE
	
class BERcodec_TYPE_SPECIFICATION_BOOLEAN_(BERcodec_NULL):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BOOLEAN_
	
class BERcodec_TYPE_SPECIFICATION_BIT_STRING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BIT_STRING
	
class BERcodec_TYPE_SPECIFICATION_INTEGER(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_INTEGER
	
class BERcodec_TYPE_SPECIFICATION_UNSIGNED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_UNSIGNED
	
class BERcodec_TYPE_SPECIFICATION_FLOATING_POINT(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_FLOATING_POINT
	
class BERcodec_TYPE_SPECIFICATION_OCTET_STRING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_OCTET_STRING
	
class BERcodec_TYPE_SPECIFICATION_VISIBLE_STRING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_VISIBLE_STRING

class BERcodec_TYPE_SPECIFICATION_BINARY_TIME(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BINARY_TIME
	
class BERcodec_TYPE_SPECIFICATION_MMS_STRING(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_MMS_STRING
	
class BERcodec_TYPE_SPECIFICATION_UTC_TIME(BERcodec_NULL):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION_UTC_TIME

#array
class BERcodec_ARRAY_PACKED(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.ARRAY_PACKED
	
class BERcodec_ARRAY_NUMBER_OF_ELEMENTS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.ARRAY_NUMBER_OF_ELEMENTS
	
class BERcodec_ARRAY_ELEMENT_TYPE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ARRAY_ELEMENT_TYPE
	
#structure
class BERcodec_STRUCTURE_PACKED(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.STRUCTURE_PACKED
	
class BERcodec_STRUCTURE_COMPONENTS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENTS


#StructComponent
class BERcodec_STRUCTURE_COMPONENT_COMPONENT_NAME(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_NAME
	
class BERcodec_STRUCTURE_COMPONENT_COMPONENT_TYPE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_TYPE

#AlternateAccess
class BERcodec_ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS

class BERcodec_ALTERNATE_ACCESS_COMPONENT(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_COMPONENT

class BERcodec_ALTERNATE_ACCESS_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_INDEX

class BERcodec_ALTERNATE_ACCESS_INDEX_RANGE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_TYPE

class BERcodec_ALTERNATE_ACCESS_ALL_ELEMENTS(BERcodec_NULL):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_ALL_ELEMENTS

class BERcodec_ALTERNATE_ACCESS_NAMED(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_NAMED

#accessSelection
class BERcodec_ACCESS_SELECTION_COMPONENT(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_COMPONENT

class BERcodec_ACCESS_SELECTION_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_INDEX

class BERcodec_ACCESS_SELECTION_INDEX_RANGE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_INDEX_RANGE

class BERcodec_ACCESS_SELECTION_ALL_ELEMENTS(BERcodec_NULL):
	tag = ASN1_Class_MMS.ACCESS_SELECTION_ALL_ELEMENTS


#indexRange
class BERcodec_LOW_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.LOW_INDEX

class BERcodec_NUMBER_OF_ELEMENTS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS

	
#named
class BERcodec_NAMED_COMPONENT_NAME(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.NAMED_COMPONENT_NAME

	
#AlternateAccessSelection
class BERcodec_ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS
	
class BERcodec_ALTERNATE_ACCESS_SELECTION_COMPONENT(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_COMPONENT
	
class BERcodec_ALTERNATE_ACCESS_SELECTION_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_INDEX
	
class BERcodec_ALTERNATE_ACCESS_SELECTION_INDEX_RANGE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_INDEX_RANGE
	
class BERcodec_ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS(BERcodec_NULL):
	tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS


#selectAlternateAccess
class BERcodec_SELECT_ALTERNATE_ACCESS_COMPONENT(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_COMPONENT
	
class BERcodec_SELECT_ALTERNATE_ACCESS_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_INDEX
	
class BERcodec_SELECT_ALTERNATE_ACCESS_INDEX_RANGE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_INDEX_RANGE
	
class BERcodec_SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS(BERcodec_NULL):
	tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS


#indexRnage
class BERcodec_LOW_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.LOW_INDEX
	
class BERcodec_NUMBER_OF_ELEMENTS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS


#IndexRangeSeq
class BERcodec_LOW_INDEX(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.LOW_INDEX
	
class BERcodec_NUMBER_OF_ELEMENTS(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS


#ReadRequest
class BERcodec_READ_REQUEST_SPECIFICATION_WITH_RESULT(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.READ_REQUEST_SPECIFICATION_WITH_RESULT
	
class BERcodec_READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION


#ReadResponse
class BERcodec_READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION
	
class BERcodec_READ_RESPONSE_LIST_OF_ACCESS_RESULT(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.READ_RESPONSE_LIST_OF_ACCESS_RESULT
	

#WriteRequest
class BERcodec_LIST_OF_DATA(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.LIST_OF_DATA	


#WriteResponse
class BERcodec_FAILURE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.FAILURE

class BERcodec_SUCCESS(BERcodec_NULL):
	tag = ASN1_Class_MMS.SUCCESS

#GetVariableAccessAttributesRequest
class BERcodec_NAME(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.NAME


#GetVariableAccessAttributesResponse
class BERcodec_MMS_DELETABLE(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.MMS_DELETABLE

class BERcodec_TYPE_SPECIFICATION(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.TYPE_SPECIFICATION


#InformationReport
class BERcodec_INFORMATION_REPORT_LIST_OF_ACCESS_RESULT(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.INFORMATION_REPORT_LIST_OF_ACCESS_RESULT


#DefineNamedVariableListRequest
class BERcodec_DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE
	

#GetNamedVariableListAttributesResponse
class BERcodec_MMS_DELETABLE(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.MMS_DELETABLE
	
class BERcodec_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE
	

#DeleteNamedVariableListRequest
class BERcodec_SCOPE_OF_DELETE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.SCOPE_OF_DELETE
	
class BERcodec_LIST_OF_VARIABLE_LIST_NAME(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.LIST_OF_VARIABLE_LIST_NAME
	
class BERcodec_DOMAIN_NAME(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.DOMAIN_NAME
	

#DeleteNamedVariableListResponse
class BERcodec_NUMBER_MATCHED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_MATCHED
	
class BERcodec_NUMBER_DELETED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.NUMBER_DELETED
	

#AccessResult
class BERcodec_FAILURE(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.FAILURE


#Data
class BERcodec_DATA_ARRAY(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.DATA_ARRAY
	
class BERcodec_DATA_STRUCTURE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.DATA_STRUCTURE
	
class BERcodec_DATA_BOOLEAN_(BERcodec_BOOLEAN):
	tag = ASN1_Class_MMS.DATA_BOOLEAN_
	
class BERcodec_DATA_BIT_STRING(BERcodec_BIT_STRING):
	tag = ASN1_Class_MMS.DATA_BIT_STRING
	
class BERcodec_DATA_INTEGER(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.DATA_INTEGER
	
class BERcodec_DATA_UNSIGNED(BERcodec_INTEGER):
	tag = ASN1_Class_MMS.DATA_UNSIGNED
	
class BERcodec_DATA_FLOATING_POINT(BERcodec_STRING):
	tag = ASN1_Class_MMS.DATA_FLOATING_POINT
	
class BERcodec_DATA_OCTET_STRING(BERcodec_STRING):
	tag = ASN1_Class_MMS.DATA_OCTET_STRING
	
class BERcodec_DATA_VISIBLE_STRING(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.DATA_VISIBLE_STRING
	
class BERcodec_DATA_BINARY_TIME(BERcodec_STRING):
	tag = ASN1_Class_MMS.DATA_BINARY_TIME

class BERcodec_DATA_MMS_STRING(BERcodec_UTF8_STRING):
	tag = ASN1_Class_MMS.DATA_MMS_STRING
	
class BERcodec_DATA_UTC_TIME(BERcodec_STRING):
	tag = ASN1_Class_MMS.DATA_UTC_TIME

	
#VariableAccessSpecification
class BERcodec_VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE
	
class BERcodec_VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME
	

#VariableDef
class BERcodec_VARIABLE_DEF_ALTERNATE_ACCESS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.VARIABLE_DEF_ALTERNATE_ACCESS
	

#VariableSpecification
class BERcodec_NAME(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.NAME


#ScatteredAccessDescription
class BERcodec_SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME(BERcodec_ISO646_STRING):
	tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME
	
class BERcodec_SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION
	
class BERcodec_SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS(BERcodec_SEQUENCE):
	tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS





	
	
'''
# [ASN1F fileds] #
#MmsPdu
class ASN1F_CONFIRMED_REQUEST_PDU(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.CONFIRMED_REQUEST_PDU

class ASN1F_CONFIRMED_RESPONSE_PDU(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.CONFIRMED_RESPONSE_PDU

class ASN1F_UNCONFIRMED_PDU(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.UNCONFIRMED_PDU

class ASN1F_INITIATE_REQUEST_PDU(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.INITIATE_REQUEST_PDU

class ASN1F_INITIATE_RESPONSE_PDU(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.INITIATE_RESPONSE_PDU

class ASN1F_INITIATE_ERROR_PDU(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.INITIATE_ERROR_PDU

#UnconfirmedService
class ASN1F_INFORMATION_REPORT(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.INFORMATION_REPORT

#ConfirmedServiceRequest
class ASN1F_GET_NAME_LIST_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.GET_NAME_LIST_REQUEST

class ASN1F_READ_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.READ_REQUEST

class ASN1F_WRITE_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.WRITE_REQUEST

class ASN1F_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST

class ASN1F_DEFINE_NAMED_VARIABLE_LIST_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_REQUEST

class ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST

class ASN1F_DELETE_NAMED_VARIABLE_LIST_REQUEST(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_REQUEST

#ConfirmedServiceResponse
class ASN1F_GET_NAMED_LIST_RESPONSE(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.GET_NAMED_LIST_RESPONSE

class ASN1F_READ_RESPONSE(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.READ_RESPONSE

class ASN1F_WRITE_RESPONSE(ASN1F_SEQUENCE_OF):
    ASN1_tag = ASN1_Class_MMS.WRITE_RESPONSE

class ASN1F_GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE

class ASN1F_DEFINE_NAMED_VARIABLE_LIST_RESPONSE(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Class_MMS.DEFINE_NAMED_VARIABLE_LIST_RESPONSE
	
class ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE
	
class ASN1F_DELETE_NAMED_VARIABLE_LIST_RESPONSE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.DELETE_NAMED_VARIABLE_LIST_RESPONSE
	
class ASN1F_VMD_SPECIFIC(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.VMD_SPECIFIC

class ASN1F_DOMAIN_SPECIFIC(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.DOMAIN_SPECIFIC
	
class ASN1F_AA_SPECIFIC(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.AA_SPECIFIC

#InitiateRequestPdu
class ASN1F_LOCAL_DETAIL_CALLING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.LOCAL_DETAIL_CALLING

class ASN1F_PROPOSED_MAX_SERV_OUTSTANDING_CALLING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLING

class ASN1F_PROPOSED_MAX_SERV_OUTSTANDING_CALLED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLED

class ASN1F_PROPOSED_DATA_STRUCTURE_NESTING_LEVEL(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.PROPOSED_DATA_STRUCTURE_NESTING_LEVEL

class ASN1F_MMS_INIT_REQUEST_DETAIL(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.MMS_INIT_REQUEST_DETAIL

#InitRequestDetail
class ASN1F_PROPOSED_VERSION_NUMBER(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.PROPOSED_VERSION_NUMBER

class ASN1F_PROPOSED_PARAMETER_CBB(ASN1F_BIT_STRING):
	ASN1_tag = ASN1_Class_MMS.PROPOSED_PARAMETER_CBB

class ASN1F_SERVICES_SUPPORTED_CALLING(ASN1F_BIT_STRING):
	ASN1_tag = ASN1_Class_MMS.SERVICES_SUPPORTED_CALLING
	
#InitiateResponsePdu
class ASN1F_LOCAL_DETAIL_CALLED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.LOCAL_DETAIL_CALLED

class ASN1F_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING

class ASN1F_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED

class ASN1F_NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL

class ASN1F_MMS_INIT_RESPONSE_DETAIL(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.MMS_INIT_RESPONSE_DETAIL

#InitResponseDetail
class ASN1F_NEGOTIATED_VERSION_NUMBER(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NEGOTIATED_VERSION_NUMBER

class ASN1F_NEGOTIATED_PARAMETER_CBB(ASN1F_BIT_STRING):
	ASN1_tag = ASN1_Class_MMS.NEGOTIATED_PARAMETER_CBB

class ASN1F_SERVICES_SUPPORTED_CALLED(ASN1F_BIT_STRING):
	ASN1_tag = ASN1_Class_MMS.SERVICES_SUPPORTED_CALLED
	
#ServiceError
class ASN1F_ERROR_CLASS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ERROR_CLASS
	
class ASN1F_ADDITIONAL_CODE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.ADDITIONAL_CODE
	
class ASN1F_ADDITIONAL_DESCRIPTION(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.ADDITIONAL_DESCRIPTION
	
#errorClass
class ASN1F_VMD_STATE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.VMD_STATE

class ASN1F_APPLICATION_REFERENCE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.APPLICATION_REFERENCE
	
class ASN1F_DEFINITION(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.DEFINITION
	
class ASN1F_RESOURCE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.RESOURCE
	
class ASN1F_SERVICE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.SERVICE
	
class ASN1F_SERVICE_PREEMPT(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.SERVICE_PREEMPT
	
class ASN1F_TIME_RESOLUTION(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TIME_RESOLUTION
	
class ASN1F_ACCESS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.ACCESS
	
class ASN1F_INITIATE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.INITIATE
	
class ASN1F_CONCLUDE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.CONCLUDE
	
class ASN1F_CANCEL(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.CANCEL
	
class ASN1F_FILE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.FILE
	
class ASN1F_OTHERS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.OTHERS

#GetNameListRequest
class ASN1F_OBJECT_CLASS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.OBJECT_CLASS
	
class ASN1F_OBJECT_SCOPE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.OBJECT_SCOPE

class ASN1F_CONTINUE_AFTER(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.CONTINUE_AFTER
	
#objectScope
class ASN1F_VMD_SPECIFIC(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.VMD_SPECIFIC
	
class ASN1F_DOMAIN_SPECIFIC(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.DOMAIN_SPECIFIC

class ASN1F_AA_SPECIFIC(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.AA_SPECIFIC
	
#ObjectClass
class ASN1F_BASIC_OBJECT_CLASS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.BASIC_OBJECT_CLASS
	
#GetNameListResponse
class ASN1F_LIST_OF_IDENTIFIER(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.LIST_OF_IDENTIFIER

class ASN1F_MORE_FOLLOWS(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.MORE_FOLLOWS

#TypeSpecification
class ASN1F_TYPE_SPECIFICATION_ARRAY(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_ARRAY
	
class ASN1F_TYPE_SPECIFICATION_STRUCTURE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_STRUCTURE
	
class ASN1F_TYPE_SPECIFICATION_BOOLEAN_(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BOOLEAN_
	
class ASN1F_TYPE_SPECIFICATION_BIT_STRING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BIT_STRING
	
class ASN1F_TYPE_SPECIFICATION_INTEGER(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_INTEGER
	
class ASN1F_TYPE_SPECIFICATION_UNSIGNED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_UNSIGNED
	
class ASN1F_TYPE_SPECIFICATION_FLOATING_POINT(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_FLOATING_POINT
	
class ASN1F_TYPE_SPECIFICATION_OCTET_STRING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_OCTET_STRING
	
class ASN1F_TYPE_SPECIFICATION_VISIBLE_STRING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_VISIBLE_STRING

class ASN1F_TYPE_SPECIFICATION_BINARY_TIME(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_BINARY_TIME
	
class ASN1F_TYPE_SPECIFICATION_MMS_STRING(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_MMS_STRING
	
class ASN1F_TYPE_SPECIFICATION_UTC_TIME(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION_UTC_TIME

#array
class ASN1F_ARRAY_PACKED(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.ARRAY_PACKED
	
class ASN1F_ARRAY_NUMBER_OF_ELEMENTS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.ARRAY_NUMBER_OF_ELEMENTS
	
class ASN1F_ARRAY_ELEMENT_TYPE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ARRAY_ELEMENT_TYPE
	
#structure
class ASN1F_STRUCTURE_PACKED(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.STRUCTURE_PACKED
	
class ASN1F_STRUCTURE_COMPONENTS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.STRUCTURE_COMPONENTS


#StructComponent
class ASN1F_STRUCTURE_COMPONENT_COMPONENT_NAME(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_NAME
	
class ASN1F_STRUCTURE_COMPONENT_COMPONENT_TYPE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_TYPE

#AlternateAccess
class ASN1F_ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS

class ASN1F_ALTERNATE_ACCESS_COMPONENT(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_COMPONENT

class ASN1F_ALTERNATE_ACCESS_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_INDEX

class ASN1F_ALTERNATE_ACCESS_INDEX_RANGE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.STRUCTURE_COMPONENT_COMPONENT_TYPE

class ASN1F_ALTERNATE_ACCESS_ALL_ELEMENTS(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_ALL_ELEMENTS

class ASN1F_ALTERNATE_ACCESS_NAMED(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_NAMED

#accessSelection
class ASN1F_ACCESS_SELECTION_COMPONENT(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.ACCESS_SELECTION_COMPONENT

class ASN1F_ACCESS_SELECTION_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.ACCESS_SELECTION_INDEX

class ASN1F_ACCESS_SELECTION_INDEX_RANGE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ACCESS_SELECTION_INDEX_RANGE

class ASN1F_ACCESS_SELECTION_ALL_ELEMENTS(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.ACCESS_SELECTION_ALL_ELEMENTS


#indexRange
class ASN1F_LOW_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.LOW_INDEX

class ASN1F_NUMBER_OF_ELEMENTS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS

	
#named
class ASN1F_NAMED_COMPONENT_NAME(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.NAMED_COMPONENT_NAME

	
#AlternateAccessSelection
class ASN1F_ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS
	
class ASN1F_ALTERNATE_ACCESS_SELECTION_COMPONENT(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_COMPONENT
	
class ASN1F_ALTERNATE_ACCESS_SELECTION_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_INDEX
	
class ASN1F_ALTERNATE_ACCESS_SELECTION_INDEX_RANGE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_INDEX_RANGE
	
class ASN1F_ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS


#selectAlternateAccess
class ASN1F_SELECT_ALTERNATE_ACCESS_COMPONENT(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_COMPONENT
	
class ASN1F_SELECT_ALTERNATE_ACCESS_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_INDEX
	
class ASN1F_SELECT_ALTERNATE_ACCESS_INDEX_RANGE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_INDEX_RANGE
	
class ASN1F_SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS


#indexRnage
class ASN1F_LOW_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.LOW_INDEX
	
class ASN1F_NUMBER_OF_ELEMENTS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS


#IndexRangeSeq
class ASN1F_LOW_INDEX(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.LOW_INDEX
	
class ASN1F_NUMBER_OF_ELEMENTS(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NUMBER_OF_ELEMENTS


#ReadRequest
class ASN1F_READ_REQUEST_SPECIFICATION_WITH_RESULT(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.READ_REQUEST_SPECIFICATION_WITH_RESULT
	
class ASN1F_READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION


#ReadResponse
class ASN1F_READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION
	
class ASN1F_READ_RESPONSE_LIST_OF_ACCESS_RESULT(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.READ_RESPONSE_LIST_OF_ACCESS_RESULT
	

#WriteRequest
class ASN1F_LIST_OF_DATA(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.LIST_OF_DATA	


#WriteResponse
class ASN1F_FAILURE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.FAILURE

class ASN1F_SUCCESS(ASN1F_NULL):
	ASN1_tag = ASN1_Class_MMS.SUCCESS

#GetVariableAccessAttributesRequest
class ASN1F_NAME(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.NAME


#GetVariableAccessAttributesResponse
class ASN1F_MMS_DELETABLE(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.MMS_DELETABLE

class ASN1F_TYPE_SPECIFICATION(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.TYPE_SPECIFICATION


#InformationReport
class ASN1F_INFORMATION_REPORT_LIST_OF_ACCESS_RESULT(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.INFORMATION_REPORT_LIST_OF_ACCESS_RESULT


#DefineNamedVariableListRequest
class ASN1F_DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE
	

#GetNamedVariableListAttributesResponse
class ASN1F_MMS_DELETABLE(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.MMS_DELETABLE
	
class ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE
	

#DeleteNamedVariableListRequest
class ASN1F_SCOPE_OF_DELETE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.SCOPE_OF_DELETE
	
class ASN1F_LIST_OF_VARIABLE_LIST_NAME(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.LIST_OF_VARIABLE_LIST_NAME
	
class ASN1F_DOMAIN_NAME(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.DOMAIN_NAME
	

#DeleteNamedVariableListResponse
class ASN1F_NUMBER_MATCHED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NUMBER_MATCHED
	
class ASN1F_NUMBER_DELETED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.NUMBER_DELETED
	

#AccessResult
class ASN1F_FAILURE(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.FAILURE


#Data
class ASN1F_DATA_ARRAY(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.DATA_ARRAY
	
class ASN1F_DATA_STRUCTURE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.DATA_STRUCTURE
	
class ASN1F_DATA_BOOLEAN_(ASN1F_BOOLEAN):
	ASN1_tag = ASN1_Class_MMS.DATA_BOOLEAN_
	
class ASN1F_DATA_BIT_STRING(ASN1F_BIT_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_BIT_STRING
	
class ASN1F_DATA_INTEGER(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.DATA_INTEGER
	
class ASN1F_DATA_UNSIGNED(ASN1F_INTEGER):
	ASN1_tag = ASN1_Class_MMS.DATA_UNSIGNED
	
class ASN1F_DATA_FLOATING_POINT(ASN1F_OCTET_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_FLOATING_POINT
	
class ASN1F_DATA_OCTET_STRING(ASN1F_OCTET_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_OCTET_STRING
	
class ASN1F_DATA_VISIBLE_STRING(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_VISIBLE_STRING
	
class ASN1F_DATA_BINARY_TIME(ASN1F_OCTET_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_BINARY_TIME

class ASN1F_DATA_MMS_STRING(ASN1F_UTF8_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_MMS_STRING
	
class ASN1F_DATA_UTC_TIME(ASN1F_OCTET_STRING):
	ASN1_tag = ASN1_Class_MMS.DATA_UTC_TIME

	
#VariableAccessSpecification
class ASN1F_VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE
	
class ASN1F_VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME
	

#VariableDef
class ASN1F_VARIABLE_DEF_ALTERNATE_ACCESS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.VARIABLE_DEF_ALTERNATE_ACCESS
	

#VariableSpecification
class ASN1F_NAME(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.NAME


#ScatteredAccessDescription
class ASN1F_SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME(ASN1F_ISO646_STRING):
	ASN1_tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME
	
class ASN1F_SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION
	
class ASN1F_SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS(ASN1F_SEQUENCE):
	ASN1_tag = ASN1_Class_MMS.SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS


	
	
	
	
	
# [MMS packet] #
#MmsPdu
class MMSconfirmed_request_pdu(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_CONFIRMED_REQUEST_PDU(ASN1F_INTEGER("invokeID"),
											ASN1F_CHOICE("ConfirmedSerivceRequest", 
															MMSget_name_list_request(),
															MMSget_name_list_request, 
															MMSread_request, 
															MMSwrite_request, 
															MMSget_variable_access_attributes_request, 
															MMSdefine_named_variable_list_request, 
															MMSget_named_variable_list_attributes_request, 
															MMSdelete_named_variable_list_request))

class MMSconfirmed_response_pdu(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_CONFIRMED_RESPONSE_PDU(ASN1F_INTEGER("invokeID"),
											ASN1F_CHOICE("ConfirmedSerivceResponse", 
															MMSget_name_list_response(),
															MMSget_name_list_response, 
															MMSread_response, 
															MMSwrite_response, 
															MMSget_variable_access_attributes_response, 
															MMSdefine_named_variable_list_response, 
															MMSget_named_variable_list_attributes_response, 
															MMSdelete_named_variable_list_response))

class MMSunconfirmed_pdu(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_UNCONFIRMED_PDU(ASN1F_CHOICE("informationReport", 
													MMSinformation_report(),
													MMSinformation_report))

class MMSinitiate_request_pdu(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_INITIATE_REQUEST_PDU(MMSlocal_detail_calling(),
											MMSproposed_max_serv_outstanding_calling(),
											MMSproposed_max_serv_outstanding_called(),
											MMSproposed_data_structure_nesting_level(),
											MMSmms_init_request_detail())

class MMSinitiate_response_pdu(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_INITIATE_RESPONSE_PDU(MMSlocal_detail_called(),
											MMSnegotiated_max_serv_outstanding_calling(),
											MMSnegotiated_max_serv_outstanding_called(),
											MMSnegotiated_data_structure_nesting_level(),
											MMSmms_init_response_detail())

class MMSinitiate_error_pdu(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_INITIATE_ERROR_PDU(MMSerror_class(),
											MMSadditional_code(),
											MMSadditional_description())

#UnconfirmedService
class MMSinformation_report(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_INFORMATION_REPORT(ASN1F_CHOICE("variableAccessSpecification", 
														MMSvariable_access_specification_list_of_variable(),
														MMSvariable_access_specification_list_of_variable,
														MMSvariable_access_specification_variable_list_name),
											MMSinformation_report_list_of_access_result())

#ConfirmedServiceRequest
class MMSget_name_list_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_NAME_LIST_REQUEST(MMSobject_class(), 
											MMSobject_scope(), 
											MMScontinue_after())

class MMSread_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_READ_REQUEST(MMSread_request_specification_with_result(),
									MMSread_request_variable_access_specification())

class MMSwrite_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_WRITE_REQUEST(ASN1F_CHOICE("variableAccessSpecification", 
													MMSvariable_access_specification_list_of_variable(),
													MMSvariable_access_specification_list_of_variable,
													MMSvariable_access_specification_variable_list_name),
									MMSlist_of_data())

class MMSget_variable_access_attributes_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_VARIABLE_ACCESS_ATTRIBUTES_REQUEST("getVariableAccessAttributes", 
																MMSname(), 
																MMSname)

class MMSdefine_named_variable_list_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DEFINE_NAMED_VARIABLE_LIST_REQUEST(ASN1F_CHOICE("variableListName",
																		MMSvmd_specific(),
																		MMSvmd_specific,
																		MMSdomain_specific,
																		MMSaa_specific),
															MMSdefined_named_variable_list_request_list_of_variable())

class MMSget_named_variable_list_attributes_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_REQUEST("getNamedVariableListAttributes",
																	MMSvmd_specific(),
																	MMSvmd_specific,
																	MMSdomain_specific,
																	MMSaa_specific)

class MMSdelete_named_variable_list_request(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DELETE_NAMED_VARIABLE_LIST_REQUEST(MMSscope_of_delete(),
															MMSlist_of_variable_list_name(),
															MMSdomain_name())

#ConfirmedServiceResponse
class MMSget_named_list_response(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_NAMED_LIST_RESPONSE(MMSlist_of_identifier(),
												MMSmore_follows())

class MMSread_response(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_READ_RESPONSE(MMSread_response_variable_access_specification(),
									MMSread_response_list_of_access_result())

class MMSwrite_response(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_WRITE_RESPONSE(ASN1F_CHOICE("write", 
													MMSfailure(),
													MMSfailure,
													MMSsuccess))

class MMSget_variable_access_attributes_response(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_VARIABLE_ACCESS_ATTRIBUTES_RESPONSE(MMSmms_deletable(),
																MMStype_specification())

class MMSdefine_named_variable_list_response(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DEFINE_NAMED_VARIABLE_LIST_RESPONSE()
	
class MMSget_named_variable_list_attributes_response(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE(MMSmms_deletable(),
																	MMSget_named_variable_list_attributes_response_list_of_variable())
	
class MMSdelete_named_variable_list_response(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DELETE_NAMED_VARIABLE_LIST_RESPONSE(MMSnumber_matched(),
															MMSnumber_deleted())

#ObjectName															
class MMSvmd_specific(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_VMD_SPECIFIC()

class MMSdomain_specific(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DOMAIN_SPECIFIC(ASN1F_ISO646_STRING(),
										ASN1F_ISO646_STRING())
	
class MMSaa_specific(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_AA_SPECIFIC()

#InitiateRequestPdu
class MMSlocal_detail_calling(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LOCAL_DETAIL_CALLING("localDetailCalling")

class MMSproposed_max_serv_outstanding_calling(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_PROPOSED_MAX_SERV_OUTSTANDING_CALLING("proposedMaxServOutstandingCalling")

class MMSproposed_max_serv_outstanding_called(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_PROPOSED_MAX_SERV_OUTSTANDING_CALLED("proposedMaxServOutstandingCalled")

class MMSproposed_data_structure_nesting_level(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_PROPOSED_DATA_STRUCTURE_NESTING_LEVEL("proposedDataStructureNestingLevel")

class MMSmms_init_request_detail(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_MMS_INIT_REQUEST_DETAIL(MMSproposed_version_number,
												MMSproposed_parameter_cbb,
												MMSservices_supported_calling)

#InitRequestDetail
class MMSproposed_version_number(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_PROPOSED_VERSION_NUMBER()

class MMSproposed_parameter_cbb(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_PROPOSED_PARAMETER_CBB()

class MMSservices_supported_calling(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SERVICES_SUPPORTED_CALLING()
	
#InitiateResponsePdu
class MMSlocal_detail_called(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LOCAL_DETAIL_CALLED()

class MMSnegotiated_max_serv_outstanding_calling(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING()

class MMSnegotiated_max_serv_outstanding_called(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED()

class MMSnegotiated_data_structure_nesting_level(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL()

class MMSmms_init_response_detail(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_MMS_INIT_RESPONSE_DETAIL(MMSnegotiated_version_number,
												MMSnegotiated_parameter_cbb,
												MMSservices_supported_called)

#InitResponseDetail
class MMSnegotiated_version_number(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NEGOTIATED_VERSION_NUMBER()

class MMSnegotiated_parameter_cbb(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NEGOTIATED_PARAMETER_CBB()

class MMSservices_supported_called(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SERVICES_SUPPORTED_CALLED()
	
#ServiceError
class MMSerror_class(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ERROR_CLASS(ASN1F_SEQUENCE(MMSvmd_state,
												MMSapplication_reference,
												MMSdefinition,
												MMSresource,
												MMSservice,
												MMSservice_preempt,
												MMStime_resolution,
												MMSaccess,
												MMSinitiate,
												MMSconclude,
												MMScancel,
												MMSfile,
												MMSothers))
	
class MMSadditional_code(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ADDITIONAL_CODE()
	
class MMSadditional_description(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ADDITIONAL_DESCRIPTION()
	
#ErrorClass
class MMSvmd_state(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_VMD_STATE()

class MMSapplication_reference(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_APPLICATION_REFERENCE()
	
class MMSdefinition(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DEFINITION()
	
class MMSresource(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_RESOURCE()
	
class MMSservice(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SERVICE()
	
class MMSservice_preempt(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SERVICE_PREEMPT()
	
class MMStime_resolution(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TIME_RESOLUTION()
	
class MMSaccess(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ACCESS()
	
class MMSinitiate(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_INITIATE()
	
class MMSconclude(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_CONCLUDE()
	
class MMScancel(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_CANCEL()
	
class MMSfile(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_FILE()
	
class MMSothers(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_OTHERS()

#GetNameListRequest
class MMSobject_class(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_OBJECT_CLASS(MMSbasic_object_class)
	
class MMSobject_scope(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_OBJECT_SCOPE(MMSvmd_specific,
									MMSdomain_specific,
									MMSaa_specific)

class MMScontinue_after(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_CONTINUE_AFTER()
	
#ObjectScope
class MMSvmd_specific(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_VMD_SPECIFIC()
	
class MMSdomain_specific(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DOMAIN_SPECIFIC()

class MMSaa_specific(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_AA_SPECIFIC()
	
#ObjectClass
class MMSbasic_object_class(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_BASIC_OBJECT_CLASS()
	
#GetNameListResponse
class MMSlist_of_identifier(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LIST_OF_IDENTIFIER(ASN1F_ISO646_STRING())

class MMSmore_follows(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_MORE_FOLLOWS()

#TypeSpecification
class MMStype_specification_array(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_ARRAY(MMSarray_packed,
												MMSarray_number_of_elements,
												MMSarray_element_type)
	
class MMStype_specification_structure(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_STRUCTURE(MMSstructure_packed,
													MMSstructure_components)
	
class MMStype_specification_boolean_(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_BOOLEAN_()
	
class MMStype_specification_bit_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_BIT_STRING()
	
class MMStype_specification_integer(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_INTEGER()
	
class MMStype_specification_unsigned(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_UNSIGNED()
	
class MMStype_specification_floating_point(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_FLOATING_POINT(ASN1F_INTEGER(),
														ASN1F_INTEGER())
	
class MMStype_specification_octet_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_OCTET_STRING()
	
class MMStype_specification_visible_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_VISIBLE_STRING()

class MMStype_specification_binary_time(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_BINARY_TIME()
	
class MMStype_specification_mms_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_MMS_STRING()
	
class MMStype_specification_utc_time(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION_UTC_TIME()

#array
class MMSarray_packed(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ARRAY_PACKED()
	
class MMSarray_number_of_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ARRAY_NUMBER_OF_ELEMENTS()
	
class MMSarray_element_type(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ARRAY_ELEMENT_TYPE(ASN1F_SEQUENCE(MMStype_specification_array(),
														MMStype_specification_structure(),
														MMStype_specification_boolean_(),
														MMStype_specification_bit_string(),
														MMStype_specification_integer(),
														MMStype_specification_unsigned(),
														MMStype_specification_floating_point(),
														MMStype_specification_octet_string(),
														MMStype_specification_visible_string(),
														MMStype_specification_binary_time(),
														MMStype_specification_mms_string(),
														MMStype_specification_utc_time()))
	
#structure
class MMSstructure_packed(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_STRUCTURE_PACKED()
	
class MMSstructure_components(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_STRUCTURE_COMPONENTS(ASN1F_SEQUENCE(MMSstructure_component_component_name,
															MMSstructure_component_component_type))


#StructComponent
class MMSstructure_component_component_name(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_STRUCTURE_COMPONENT_COMPONENT_NAME()
	
class MMSstructure_component_component_type(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_STRUCTURE_COMPONENT_COMPONENT_TYPE(ASN1F_SEQUENCE(MMStype_specification_array(),
														MMStype_specification_structure(),
														MMStype_specification_boolean_(),
														MMStype_specification_bit_string(),
														MMStype_specification_integer(),
														MMStype_specification_unsigned(),
														MMStype_specification_floating_point(),
														MMStype_specification_octet_string(),
														MMStype_specification_visible_string(),
														MMStype_specification_binary_time(),
														MMStype_specification_mms_string(),
														MMStype_specification_utc_time()))

#AlternateAccess
class MMSalternate_access_select_alternate_access(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_SELECT_ALTERNATE_ACCESS(ASN1F_SEQUENCE(MMSaccess_selection_component(),
																			MMSaccess_selection_index(),
																			MMSaccess_selection_index_range(),
																			MMSalternate_access_all_elements()),
																ASN1F_SEQUENCE_OF(ASN1F_SEQUENCE(MMSalternate_access_select_alternate_access(),
																								MMSalternate_access_component(),
																								MMSalternate_access_index(),
																								MMSalternate_access_index_range(),
																								MMSalternate_access_all_elements(),
																								MMSalternate_access_named())))

class MMSalternate_access_component(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_COMPONENT()

class MMSalternate_access_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_INDEX()

class MMSalternate_access_index_range(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_INDEX_RANGE(MMSlow_index(),
													MMSnumber_of_elements())

class MMSalternate_access_all_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_ALL_ELEMENTS()

class MMSalternate_access_named(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_NAMED(MMSnamed_component_name(),
												ASN1F_SEQUENCE(MMSalternate_access_selection_select_alternate_access(),
																MMSalternate_access_selection_component(),
																MMSalternate_access_selection_index(),
																MMSalternate_access_selection_index_range(),
																MMSalternate_access_selection_alle_elements()))

#accessSelection
class MMSaccess_selection_component(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ACCESS_SELECTION_COMPONENT()

class MMSaccess_selection_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ACCESS_SELECTION_INDEX()

class MMSaccess_selection_index_range(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ACCESS_SELECTION_INDEX_RANGE(MMSlow_index(),
													MMSnumber_of_elements())

class MMSaccess_selection_all_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ACCESS_SELECTION_ALL_ELEMENTS()


#indexrange
class MMSlow_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LOW_INDEX()

class MMSnumber_of_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NUMBER_OF_ELEMENTS()

	
#named
class MMSnamed_component_name(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NAMED_COMPONENT_NAME()

	
#AlternateAccesSelection
class MMSalternate_access_selection_select_alternate_access(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_SELECTION_SELECT_ALTERNATE_ACCESS(MMSselect_alternate_access_component(),
																			MMSselect_alternate_access_index(),
																			MMSselect_alternate_access_index_range(),
																			MMSselect_alternate_access_all_elements())
	
class MMSalternate_access_selection_component(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_SELECTION_COMPONENT()
	
class MMSalternate_access_selection_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_SELECTION_INDEX()
	
class MMSalternate_access_selection_index_range(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_SELECTION_INDEX_RANGE()
	
class MMSalternate_access_selection_alle_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_ALTERNATE_ACCESS_SELECTION_ALLE_ELEMENTS()


#selectAlternateAccess
class MMSselect_alternate_access_component(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SELECT_ALTERNATE_ACCESS_COMPONENT()
	
class MMSselect_alternate_access_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SELECT_ALTERNATE_ACCESS_INDEX()
	
class MMSselect_alternate_access_index_range(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SELECT_ALTERNATE_ACCESS_INDEX_RANGE(MMSlow_index(),
															MMSnumber_of_elements())
	
class MMSselect_alternate_access_all_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SELECT_ALTERNATE_ACCESS_ALL_ELEMENTS()


#indexRnage
class MMSlow_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LOW_INDEX()
	
class MMSnumber_of_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NUMBER_OF_ELEMENTS()


#IndexRangeSeq
class MMSlow_index(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LOW_INDEX()
	
class MMSnumber_of_elements(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NUMBER_OF_ELEMENTS()


#ReadRequest
class MMSread_request_specification_with_result(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_READ_REQUEST_SPECIFICATION_WITH_RESULT()
	
class MMSread_request_variable_access_specification(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION(MMSvariable_access_specification_list_of_variable(),
																	MMSvariable_access_specification_variable_list_name())


#ReadResponse
class MMSread_response_variable_access_specification(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_READ_RESPONSE_VARIABLE_ACCESS_SPECIFICATION(MMSvariable_access_specification_list_of_variable(),
																	MMSvariable_access_specification_variable_list_name())
	
class MMSread_response_list_of_access_result(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_READ_RESPONSE_LIST_OF_ACCESS_RESULT(ASN1F_SEQUENCE(MMSfailure(),
																		ASN1F_SEQUENCE(MMSdata_array(),
																						MMSdata_structure(),
																						MMSdata_boolean_(),
																						MMSdata_bit_string(),
																						MMSdata_integer(),
																						MMSdata_unsigned(),
																						MMSdata_floating_point(),
																						MMSdata_octet_string(),
																						MMSdata_visible_string(),
																						MMSdata_binary_time(),
																						MMSdata_mms_string(),
																						MMSdata_utc_time())))
	

#WriteRequest
class MMSlist_of_data(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LIST_OF_DATA(ASN1F_SEQUENCE(MMSdata_array(),
												MMSdata_structure(),
												MMSdata_boolean_(),
												MMSdata_bit_string(),
												MMSdata_integer(),
												MMSdata_unsigned(),
												MMSdata_floating_point(),
												MMSdata_octet_string(),
												MMSdata_visible_string(),
												MMSdata_binary_time(),
												MMSdata_mms_string(),
												MMSdata_utc_time()))


#WriteResponse
class MMSfailure(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_FAILURE()

class MMSsuccess(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SUCCESS()

#GetVariableAccessAttributesRequest
class MMSname(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NAME(ASN1F_SEQUENCE(MMSvmd_specific(),
										MMSdomain_specific(),
										MMSaa_specific()))


#GetVariableAccessAttributesResponse
class MMSmms_deletable(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_MMS_DELETABLE()

class MMStype_specification(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_TYPE_SPECIFICATION(ASN1F_SEQUENCE(MMStype_specification_array(),
														MMStype_specification_structure(),
														MMStype_specification_boolean_(),
														MMStype_specification_bit_string(),
														MMStype_specification_integer(),
														MMStype_specification_unsigned(),
														MMStype_specification_floating_point(),
														MMStype_specification_octet_string(),
														MMStype_specification_visible_string(),
														MMStype_specification_binary_time(),
														MMStype_specification_mms_string(),
														MMStype_specification_utc_time()))


#InformationReport
class MMSinformation_report_list_of_access_result(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_INFORMATION_REPORT_LIST_OF_ACCESS_RESULT(ASN1F_SEQUENCE(MMSfailure(),
																			ASN1F_SEQUENCE(MMSdata_array(),
																						MMSdata_structure(),
																						MMSdata_boolean_(),
																						MMSdata_bit_string(),
																						MMSdata_integer(),
																						MMSdata_unsigned(),
																						MMSdata_floating_point(),
																						MMSdata_octet_string(),
																						MMSdata_visible_string(),
																						MMSdata_binary_time(),
																						MMSdata_mms_string(),
																						MMSdata_utc_time())))


#DefineNamedVariableListRequest
class MMSdefined_named_variable_list_request_list_of_variable(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DEFINED_NAMED_VARIABLE_LIST_REQUEST_LIST_OF_VARIABLE(ASN1F_SEQUENCE(ASN1F_SEQUENCE(MMSname()),
																							MMSvariable_def_alternate_access()))
	

#GetNamedVariableListAttributesResponse
class MMSmms_deletable(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_MMS_DELETABLE()
	
class MMSget_named_variable_list_attributes_response_list_of_variable(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_GET_NAMED_VARIABLE_LIST_ATTRIBUTES_RESPONSE_LIST_OF_VARIABLE(ASN1F_SEQUENCE(ASN1F_SEQUENCE(MMSname()),
																							MMSvariable_def_alternate_access()))
	

#DeleteNamedVariableListRequest
class MMSscope_of_delete(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SCOPE_OF_DELETE()
	
class MMSlist_of_variable_list_name(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_LIST_OF_VARIABLE_LIST_NAME(ASN1F_SEQUENCE(MMSvmd_specific(),
																MMSdomain_specific(),
																MMSaa_specific()))
	
class MMSdomain_name(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DOMAIN_NAME()
	

#DeleteNamedVariableListResponse
class MMSnumber_matched(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NUMBER_MATCHED()
	
class MMSnumber_deleted(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NUMBER_DELETED()
	

#AccessResult
class MMSfailure(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_FAILURE()


#Data
class MMSdata_array(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_ARRAY(ASN1F_SEQUENCE(MMSdata_array(),
												MMSdata_structure(),
												MMSdata_boolean_(),
												MMSdata_bit_string(),
												MMSdata_integer(),
												MMSdata_unsigned(),
												MMSdata_floating_point(),
												MMSdata_octet_string(),
												MMSdata_visible_string(),
												MMSdata_binary_time(),
												MMSdata_mms_string(),
												MMSdata_utc_time()))
	
class MMSdata_structure(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_STRUCTURE(ASN1F_SEQUENCE(MMSdata_array(),
													MMSdata_structure(),
													MMSdata_boolean_(),
													MMSdata_bit_string(),
													MMSdata_integer(),
													MMSdata_unsigned(),
													MMSdata_floating_point(),
													MMSdata_octet_string(),
													MMSdata_visible_string(),
													MMSdata_binary_time(),
													MMSdata_mms_string(),
													MMSdata_utc_time()))
	
class MMSdata_boolean_(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_BOOLEAN_()
	
class MMSdata_bit_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_BIT_STRING()
	
class MMSdata_integer(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_INTEGER()
	
class MMSdata_unsigned(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_UNSIGNED()
	
class MMSdata_floating_point(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_FLOATING_POINT()
	
class MMSdata_octet_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_OCTET_STRING()
	
class MMSdata_visible_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_VISIBLE_STRING()
	
class MMSdata_binary_time(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_BINARY_TIME()

class MMSdata_mms_string(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_MMS_STRING()
	
class MMSdata_utc_time(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_DATA_UTC_TIME()

	
#VariableAccessSpecification
class MMSvariable_access_specification_list_of_variable(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE(ASN1F_SEQUENCE(ASN1F_SEQUENCE(MMSname()),
																									MMSvariable_def_alternate_access()))
	
class MMSvariable_access_specification_variable_list_name(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME(ASN1F_SEQUENCE(MMSvmd_specific(),
																					MMSdomain_specific(),
																					MMSaa_specific()))
	

#VariableDef
class MMSvariable_def_alternate_access(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_VARIABLE_DEF_ALTERNATE_ACCESS(ASN1F_SEQUENCE(MMSalternate_access_select_alternate_access(),
																	MMSalternate_access_component(),
																	MMSalternate_access_index(),
																	MMSalternate_access_index_range(),
																	MMSalternate_access_all_elements(),
																	MMSalternate_access_named()))
	

#VariableSpecification
class MMSname(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_NAME(ASN1F_SEQUENCE(MMSvmd_specific(),
										MMSdomain_specific(),
										MMSaa_specific()))


#ScatteredAccessDescription
class MMSscattered_access_description_component_name(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SCATTERED_ACCESS_DESCRIPTION_COMPONENT_NAME()
	
class MMSscattered_access_description_variable_specification(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SCATTERED_ACCESS_DESCRIPTION_VARIABLE_SPECIFICATION(ASN1F_SEQUENCE(MMSname()))
	
class MMSscattered_access_description_alternate_access(ASN1_Packet):
	ASN1_codec = ASN1_Codecs.BER
	ASN1_root = ASN1F_SCATTERED_ACCESS_DESCRIPTION_ALTERNATE_ACCESS(ASN1F_SEQUENCE(MMSalternate_access_select_alternate_access(),
																					MMSalternate_access_component(),
																					MMSalternate_access_index(),
																					MMSalternate_access_index_range(),
																					MMSalternate_access_all_elements(),
																					MMSalternate_access_named()))




class MMS(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_SEQUENCE("PDU", MMSconfirmed_request(),
            MMSconfirmed_request, MMSconfirmed_response, MMSunconfirmed,
            MMSinitiate_request, MMSinitiate_response, MMSinitiate_error)

'''

z=ASN1_CONFIRMED_REQUEST_PDU([
ASN1_INTEGER(198),
ASN1_WRITE_REQUEST([
ASN1_VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE([
ASN1_SEQUENCE([
ASN1_NAME([
ASN1_DOMAIN_SPECIFIC([
ASN1_ISO646_STRING("TEMPLATELD0"),
ASN1_ISO646_STRING("MHAI1$MX$HPhV$phsAHar")])])
])]),
ASN1_LIST_OF_DATA([
ASN1_DATA_ARRAY([
ASN1_DATA_FLOATING_POINT("ABCDE")])])])])

class ASN1_Class_TEST(ASN1_Class_UNIVERSAL):
    name="TEST"
    HELLO=0xa1
class ASN1_TEST(ASN1_SEQUENCE):
    tag = ASN1_Class_TEST.HELLO
class BERcodec_TEST(BERcodec_SEQUENCE):
    tag = ASN1_Class_TEST.HELLO
z=ASN1_TEST([ASN1_ISO646_STRING("MHAI1$MX$HPhV$phsAHar")])
#z=ASN1_SEQUENCE([ASN1_ISO646_STRING("MHAI1$MX$HPhV$phsAHar")])
hexdump(z)

